
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: nhartland/love-build@v1-beta
      id: love-build
      with:
        app_name: 'shooter'
        love_version: '11.3'

    - uses: actions/upload-artifact@v1
      with:
        name: macos-build
        path: ${{ steps.love-build.outputs.macos-filename }}

    - uses: actions/upload-artifact@v1
      with:
        name: win32-build
        path: ${{ steps.love-build.outputs.win32-filename }}

    - uses: actions/upload-artifact@v1
      with:
        name: love-build
        path: ${{ steps.love-build.outputs.love-filename }}
